In [1]:
import pandas as pd

In [2]:
import sys

sys.path.append("..")

In [ ]:
from config import POPULATION_COMMUNE_PATH

population_raw = pd.read_csv(POPULATION_COMMUNE_PATH, sep="|")

display(population_raw)

,CD_REFNIS,TX_DESCR_NL,TX_DESCR_FR,CD_DSTR_REFNIS,TX_ADM_DSTR_DESCR_NL,TX_ADM_DSTR_DESCR_FR,CD_PROV_REFNIS,TX_PROV_DESCR_NL,TX_PROV_DESCR_FR,CD_RGN_REFNIS,...,TX_RGN_DESCR_FR,CD_SEX,CD_NATLTY,TX_NATLTY_NL,TX_NATLTY_FR,CD_CIV_STS,TX_CIV_STS_NL,TX_CIV_STS_FR,CD_AGE,MS_POPULATION
0,11001,Aartselaar,Aartselaar,11000,Arrondissement Antwerpen,Arrondissement d’Anvers,10000,Provincie Antwerpen,Province d’Anvers,2000,...,Région flamande,F,BEL,Belgen,Belges,4,Gescheiden,Divorcé,67,14
1,11001,Aartselaar,Aartselaar,11000,Arrondissement Antwerpen,Arrondissement d’Anvers,10000,Provincie Antwerpen,Province d’Anvers,2000,...,Région flamande,F,BEL,Belgen,Belges,4,Gescheiden,Divorcé,93,1
2,11001,Aartselaar,Aartselaar,11000,Arrondissement Antwerpen,Arrondissement d’Anvers,10000,Provincie Antwerpen,Province d’Anvers,2000,...,Région flamande,F,BEL,Belgen,Belges,4,Gescheiden,Divorcé,81,3
3,11001,Aartselaar,Aartselaar,11000,Arrondissement Antwerpen,Arrondissement d’Anvers,10000,Provincie Antwerpen,Province d’Anvers,2000,...,Région flamande,M,BEL,Belgen,Belges,4,Gescheiden,Divorcé,67,12
4,11001,Aartselaar,Aartselaar,11000,Arrondissement Antwerpen,Arrondissement d’Anvers,10000,Provincie Antwerpen,Province d’Anvers,2000,...,Région flamande,F,BEL,Belgen,Belges,4,Gescheiden,Divorcé,68,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466817,93090,Viroinval,Viroinval,93000,Arrondissement Philippeville,Arrondissement de Philippeville,90000,Provincie Namen,Province de Namur,3000,...,Région wallonne,F,BEL,Belgen,Belges,2,Gehuwd,Marié,77,19
466818,93090,Viroinval,Viroinval,93000,Arrondissement Philippeville,Arrondissement de Philippeville,90000,Provincie Namen,Province de Namur,3000,...,Région wallonne,F,BEL,Belgen,Belges,2,Gehuwd,Marié,85,1
466819,93090,Viroinval,Viroinval,93000,Arrondissement Philippeville,Arrondissement de Philippeville,90000,Provincie Namen,Province de Namur,3000,...,Région wallonne,M,BEL,Belgen,Belges,2,Gehuwd,Marié,83,1
466820,93090,Viroinval,Viroinval,93000,Arrondissement Philippeville,Arrondissement de Philippeville,90000,Provincie Namen,Province de Namur,3000,...,Région wallonne,M,BEL,Belgen,Belges,2,Gehuwd,Marié,58,17
466821,93090,Viroinval,Viroinval,93000,Arrondissement Philippeville,Arrondissement de Philippeville,90000,Provincie Namen,Province de Namur,3000,...,Région wallonne,M,BEL,Belgen,Belges,2,Gehuwd,Marié,91,4

In [4]:

list(population_raw.columns)

['CD_REFNIS',
 'TX_DESCR_NL',
 'TX_DESCR_FR',
 'CD_DSTR_REFNIS',
 'TX_ADM_DSTR_DESCR_NL',
 'TX_ADM_DSTR_DESCR_FR',
 'CD_PROV_REFNIS',
 'TX_PROV_DESCR_NL',
 'TX_PROV_DESCR_FR',
 'CD_RGN_REFNIS',
 'TX_RGN_DESCR_NL',
 'TX_RGN_DESCR_FR',
 'CD_SEX',
 'CD_NATLTY',
 'TX_NATLTY_NL',
 'TX_NATLTY_FR',
 'CD_CIV_STS',
 'TX_CIV_STS_NL',
 'TX_CIV_STS_FR',
 'CD_AGE',
 'MS_POPULATION']

In [5]:
population_clean = population_raw[
    ['CD_REFNIS',
 #'TX_DESCR_NL',
 'TX_DESCR_FR',
 'CD_DSTR_REFNIS',
 #'TX_ADM_DSTR_DESCR_NL',
 'TX_ADM_DSTR_DESCR_FR',
 'CD_PROV_REFNIS',
 #'TX_PROV_DESCR_NL',
 'TX_PROV_DESCR_FR',
 'CD_RGN_REFNIS',
 #'TX_RGN_DESCR_NL',
 'TX_RGN_DESCR_FR',
 'CD_SEX',
 'CD_NATLTY',
 #'TX_NATLTY_NL',
 'TX_NATLTY_FR',
 'CD_CIV_STS',
 #'TX_CIV_STS_NL',
 'TX_CIV_STS_FR',
 'CD_AGE',
 'MS_POPULATION']
]

In [6]:
population_clean.sample(10)

,CD_REFNIS,TX_DESCR_FR,CD_DSTR_REFNIS,TX_ADM_DSTR_DESCR_FR,CD_PROV_REFNIS,TX_PROV_DESCR_FR,CD_RGN_REFNIS,TX_RGN_DESCR_FR,CD_SEX,CD_NATLTY,TX_NATLTY_FR,CD_CIV_STS,TX_CIV_STS_FR,CD_AGE,MS_POPULATION
321334,61079,Anthisnes,61000,Arrondissement de Huy,60000,Province de Liège,3000,Région wallonne,M,ETR,non-Belges,2,Marié,76,2
417934,82039,Bastogne,82000,Arrondissement de Bastogne,80000,Province du Luxembourg,3000,Région wallonne,M,ETR,non-Belges,4,Divorcé,60,2
28423,12014,Heist-op-den-Berg,12000,Arrondissement de Malines,10000,Province d’Anvers,2000,Région flamande,M,ETR,non-Belges,4,Divorcé,43,3
269936,52048,Montigny-le-Tilleul,52000,Arrondissement de Charleroi,50000,Province du Hainaut,3000,Région wallonne,F,BEL,Belges,2,Marié,80,9
87498,23038,Kampenhout,23000,Arrondissement de Hal-Vilvorde,20001,Province du Brabant flamand,2000,Région flamande,M,BEL,Belges,1,Célibataire,84,1
28873,12014,Heist-op-den-Berg,12000,Arrondissement de Malines,10000,Province d’Anvers,2000,Région flamande,F,BEL,Belges,1,Célibataire,94,1
287121,55050,Ecaussinnes,55000,Arrondissement de Soignies,50000,Province du Hainaut,3000,Région wallonne,F,BEL,Belges,4,Divorcé,48,11
308566,58001,La Louvière,58000,Arrondissement de La Louvière,50000,Province du Hainaut,3000,Région wallonne,M,ETR,non-Belges,4,Divorcé,86,3
321270,61079,Anthisnes,61000,Arrondissement de Huy,60000,Province de Liège,3000,Région wallonne,M,BEL,Belges,3,Veuf,69,1
41985,13011,Herentals,13000,Arrondissement de Turnhout,10000,Province d’Anvers,2000,Région flamande,F,BEL,Belges,2,Marié,41,81

In [7]:
population_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466822 entries, 0 to 466821
Data columns (total 15 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   CD_REFNIS             466822 non-null  int64
 1   TX_DESCR_FR           466822 non-null  object
 2   CD_DSTR_REFNIS        466822 non-null  int64
 3   TX_ADM_DSTR_DESCR_FR  466822 non-null  object
 4   CD_PROV_REFNIS        466822 non-null  int64
 5   TX_PROV_DESCR_FR      466822 non-null  object
 6   CD_RGN_REFNIS         466822 non-null  int64
 7   TX_RGN_DESCR_FR       466822 non-null  object
 8   CD_SEX                466822 non-null  object
 9   CD_NATLTY             466822 non-null  object
 10  TX_NATLTY_FR          466822 non-null  object
 11  CD_CIV_STS            466822 non-null  int64
 12  TX_CIV_STS_FR         466822 non-null  object
 13  CD_AGE                466822 non-null  int64
 14  MS_POPULATION         466822 non-null  int64
dtypes: int64(7), object(8)
memory usage: 53.4+ MB

In [8]:
#population_clean["CD_AGE"].min()
population_clean["CD_AGE"].max()

np.int64(100)

In [9]:
(population_clean.isna().mean()*100).round(2)

CD_REFNIS               0.0
TX_DESCR_FR             0.0
CD_DSTR_REFNIS          0.0
TX_ADM_DSTR_DESCR_FR    0.0
CD_PROV_REFNIS          0.0
TX_PROV_DESCR_FR        0.0
CD_RGN_REFNIS           0.0
TX_RGN_DESCR_FR         0.0
CD_SEX                  0.0
CD_NATLTY               0.0
TX_NATLTY_FR            0.0
CD_CIV_STS              0.0
TX_CIV_STS_FR           0.0
CD_AGE                  0.0
MS_POPULATION           0.0
dtype: float64

In [10]:
population_clean["MS_POPULATION"].describe()

count    466822.000000
mean         25.332034
std          66.193201
min           1.000000
25%           2.000000
50%           7.000000
75%          25.000000
max        2950.000000
Name: MS_POPULATION, dtype: float64

In [11]:
population_clean["MS_POPULATION"].sum()

np.int64(11825551)

In [12]:
population_clean["TX_NATLTY_FR"].unique()

array(['Belges', 'non-Belges'], dtype=object)

In [13]:
population_liege = population_clean[population_clean["TX_DESCR_FR"] == "Liège"]
population_liege.shape

(1240, 15)

In [14]:
population_liege["CD_AGE"].unique()

array([ 66,  94,  89,  48,  47,  75,  56,  21,  60,  92,  59,  46,  96,
        90,  49,  53,  45,  81,  20,  93,  41,  61,  23,  73,  62,  38,
        83,  27,  44,  24,  87,  42,  52,  40,  84,  68,  82,  91,  34,
        95,  65,  58,  19,  86,  72,  64,  67,  22,  88,  30,  79,  33,
        74,  63,  54,  55,  36,  77,  39,  31,  37,  70,  78,  28,  71,
        69,  85,  80,  50,  29,  26,  32,  76,  18,  43,  98,  97,  99,
        35,  51,  57, 100,  25,   6,  16,   8,  10,  15,  11,   7,   0,
         9,   2,   4,  13,   3,  12,   5,   1,  17,  14])